version: '3.9'

services:

  lid-service:
    stdin_open: true
    tty: true
    image: beetee/lid-service:1.0.0-build
    build:
      context: .
      dockerfile: dockerfile.dev
      target: build
    env_file:
      - ./main.env
    volumes:
      - ./proto:/proto
      - ./src:/src
      - ./weights:/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 40053:50053
    working_dir: /src
    command:
      [
        "sh",
        "-c",
        "python -m grpc_tools.protoc -I / --python_out=/src --pyi_out=/src --grpc_python_out=/src /proto/lid.proto && python serve.py"
      ]
