# docker build -t beetee/lid-service:1.0.0-build -f dockerfile.dev --target build .
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime as build

SHELL ["/bin/bash", "-c"]

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONFAULTHANDLER=1
ENV TZ=Asia/Singapore

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# set explicit directory path to libcudnn
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/conda/lib/python3.10/site-packages/torch/lib"

# Install pip requirements
COPY requirements.txt .

RUN python -m venv /venv && \
    source /venv/bin/activate && \
    python -m pip install --upgrade --no-cache-dir pip && \
    python -m pip install -r requirements.txt

ENV PATH="/venv/bin:${PATH}"

COPY ./src /src
COPY ./proto /proto

RUN python -m grpc_tools.protoc \
    -I / \
    --python_out=/src \
    --pyi_out=/src \
    --grpc_python_out=/src \
    /proto/lid.proto




