# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lid.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/lid.proto\"3\n\x1dLanguageIdentificationRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"K\n\x1eLanguageIdentificationResponse\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32l\n\x12LanguageIdentifier\x12V\n\x11identify_language\x12\x1e.LanguageIdentificationRequest\x1a\x1f.LanguageIdentificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.lid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LANGUAGEIDENTIFICATIONREQUEST']._serialized_start=19
  _globals['_LANGUAGEIDENTIFICATIONREQUEST']._serialized_end=70
  _globals['_LANGUAGEIDENTIFICATIONRESPONSE']._serialized_start=72
  _globals['_LANGUAGEIDENTIFICATIONRESPONSE']._serialized_end=147
  _globals['_LANGUAGEIDENTIFIER']._serialized_start=149
  _globals['_LANGUAGEIDENTIFIER']._serialized_end=257
# @@protoc_insertion_point(module_scope)
